import Head from "next/head";
import Background from "../component/Background";
import Topbar from "../component/topbar";
import About from "../component/About";
import Quotes from "../component/insirationalQuotes";
import Tag from "../component/tag";

import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Kavita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />

      <div>
        <About />
      </div>
    </div>
  );
}
